### ISSUE TITLE
Didn't work for me at all

### ISSUE THREAD

**Issue by nkmlombardi** [egoist/sao#15]
On my Mac, the first install of template-vuepack worked but everything after that didn't. The template was also broken. Just tried again on my windows machine and sao doesn't create the directories at all. The --install flag also didn't work and I had to use npm to install them. Even after that sao didn't end up doing anything at all after the installation questions.

MacOSX Terminal & Windows Powershell
Versions:
node -v = v7.0.0
npm -v = 3.10.8
sao -v = 0.16.3
vue-cli = 2.7.0

**Comment by egoist** [comment]
oops, https://github.com/egoist/kopy ignores all path matched `/node_modules/` 😐

**Comment by nkmlombardi** [comment]
Let me know if there's anything I can do to help! Appreciate your contributions to the community.

**Comment by egoist** [comment]
it should work now ;)
