### ISSUE TITLE
how do you create your official website & deploy it? (empty issue body)

### ISSUE THREAD

**Issue by zzz6519003** [egoist/sao#17]

**Comment by egoist** [comment]
what? you mean https://github.com/egoist/docute ?

**Comment by zzz6519003** [comment]
amazing! inspired by vue?XD

how do u deploy https://sao.js.org/#/

**Comment by egoist** [comment]
It's here https://github.com/saojs/sao/tree/master/docs served by github pages, I don't need to deploy it.
