### ISSUE TITLE
`when` in prompts is not helpful.

### ISSUE THREAD

**Issue by SidKwok** [egoist/sao#19]
<img width="367" alt="7f90f14e-5655-46c1-a5cf-4df44948da96" src="https://cloud.githubusercontent.com/assets/13268747/22783982/18dacb42-ef09-11e6-80f5-7ca5bfe34956.png">

![b1eef8ac-7f62-4f41-96ee-4a3f6db38abe](https://cloud.githubusercontent.com/assets/13268747/22783959/04196ba0-ef09-11e6-96ad-35041a6b4676.png)

**Comment by egoist** [comment]
https://github.com/SBoudrias/Inquirer.js#question

- when: (Function, Boolean) Receive the current user answers hash and should return true or false depending on whether or not this question should be asked. The value can also be a simple boolean.

maybe we can add `expression support` later.

**Comment by SidKwok** [comment]
It is [template-vue-webpack](https://github.com/egoist/template-vue-webpack)'s `sao.js`.

This issue will be solved when rewrote with this:
```
...
when: ({lint}) => lint,
...
```
