### ISSUE TITLE
Error when using the template which is installed by npm

### ISSUE THREAD

**Issue by zcong1993** [egoist/sao#20]
because the `yarn's global modules path` is diffrent from `npm's` .

on OSX, yarn's is `~/.config/yarn/global/node_modules`, and npm's is `/usr/local/lib/node_modules`

the path you search is depend on how to install `sao` 

can see [https://github.com/egoist/sao/blob/master/lib/utils.js#L16](https://github.com/egoist/sao/blob/master/lib/utils.js#L16)

so, when I using the template installed by `npm`, but `sao` is installed by `yarn`, got `donn't have template error`

**Comment by egoist** [comment]
then just reinstall it with yarn

**Comment by egoist** [comment]
Closed since this is not a bug
