### ISSUE TITLE
sao会添加已经删除了的文件到template中

### ISSUE THREAD

**Issue by SidKwok** [egoist/sao#22]
可以看我创建的[模版仓库](https://github.com/SidKwok/sao-test-repo)。

我第一次提交的时候添加了一个`old-file.js`，然后用删除了这个文件，提交上去，然后再添加一个`new-file.js`，提交上去。这时候我的`template`里面已经没有`old-file.js`了，但是用命令`sao SidKwok/sao-test-repo sao-test --install`生成的模版里面，`old-file.js`依然存在。

麻烦帮忙看看这一个问题。

**Comment by egoist** [comment]
默认会使用缓存，你需要 `sao template --install` 来跳过缓存重新下载模板。本地测试可以用本地路径: `sao ../path/tp/template`

**Comment by SidKwok** [comment]
`sao SidKwok/sao-test-repo sao-test --install`
这个命令已经跳过缓存了啊，但是`old-file.js`还是存在

**Comment by egoist** [comment]
啊，可能 https://github.com/flipxfx/download-git-repo 没有清理缓存，你看看 `ls ~/.sao/repos/SidKwok-sao-test-repo` 有没有那个文件

**Comment by SidKwok** [comment]
```
ls ~/.sao/repos/SidKwok-sao-test-repo/template 
new-file.js old-file.js
```
啊，有啊！
所以这是bug吗？

**Comment by egoist** [comment]
Fixed in `v0.16.10`

**Comment by SidKwok** [comment]
Thanks
