### ISSUE TITLE
Issue using --install with cached git templates

### ISSUE THREAD

**Issue by w33ble** [egoist/sao#27]
I saw this option in the help menu

> --install       Always install template before generating

I expected that if I use this with a cached template, it would download/update that template before using it. This might work for templates on npm, but when I try using it with a git template, I get an error:

```
$ sao --templates

  Templates installed from npm:

  none

  Templates installed from git:

  w33ble/node-module-template
```
```
$ sao --install w33ble/node-module-template test
> Installing template-test...
ERROR Error occurs during installing package.

warning No license field
error Couldn't find package "template-test" on the "npm" registry.
ERROR Template path "/Users/d33t/.nvm/versions/node/v6.10.2/lib/node_modules/template-test" does not exist!
```

Looks like it skips the template name and tries to use *test* as the template name and attempts to grab the template from npm. 

If I use the command wrong, by adding a bogus first argument (`wat` below), it does work:

```
$ sao --install wat w33ble/node-module-template test
INFO Since this template is a git repo, we're installing its dependencies now.
yarn install v0.21.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
success Nothing to install.
success Saved lockfile.
✨  Done in 0.35s.
...
```

Looks like a command parsing issue.

**Comment by egoist** [comment]
Fixed in `v0.19.4`
