### ISSUE TITLE
`move` is not work in directory

### ISSUE THREAD

**Issue by x4storm** [egoist/sao#29]
```
module.exports = {
  prompts: {
    project_name: {
      role: 'folder:name',
      message: '请输入项目名称:',
    },
  },
  enforceNewFolder: true,
  move: {
    'module': 'project_name'
  },
  post(context){
    // context.init()
  }
}
````

**Comment by egoist** [comment]
hmm, I don't understand your issue.

each entry of `move` is the original path, and the value of it is the target path

**Comment by x4storm** [comment]
I'm transplanting the official template of scrapy.
It will dynamically generate the name of the secondary directory.

I saw the `majo` and `kopy` source code. Finaly, I used the `post`  to achieve the purpose.

**Comment by egoist** [comment]
Oh, it seems useful to support expressions in `move`. 🙂

**Comment by egoist** [comment]
`move` can be a function now: https://sao.js.org/#/create?id=move
