### ISSUE TITLE
Document how to develop sao locally and test it

### ISSUE THREAD

**Issue by niftylettuce** [egoist/sao#42]
e.g. we should tell people they can do `sao ./ output` from the root of their folder and add `output/` to `.gitignore`, and we might also want to mention `targetPath` set to `path.join(__dirname, 'output')` or something in ava test

**Comment by egoist** [comment]
hmm how are you testing in AVA? you don't need `targetPath` if you use `sao.mockPrompt` https://sao.js.org/#/advanced/testhttps://sao.js.org/#/advanced/test

**Comment by niftylettuce** [comment]
@egoist why do you use it here? https://github.com/egoist/sao/blob/master/test/index.test.js#L9

**Comment by egoist** [comment]
oh that's not really necessary, you know that we can use `default: ':folderName:'` keyword, we actually get the `folderName` from `targetPath`, but `targetPath` in `sao.mockPrompt` is already set to a random value, and it will not really write any files to disk.
